name: Publish Package to npmjs
on:
  push:
    branch: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm run build
      - run: mv build/* public/
      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          # The name of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_name: Github

          # The email of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_email: workflow@github.com

          # Determines the way the action fills missing author name and email. Three options are available:
          # - github_actor -> UserName <UserName@users.noreply.github.com>
          # - user_info -> Your Display Name <your-actual@email.com>
          # - github_actions -> github-actions <email associated with the github logo>
          # Default: github_actor
          default_author: github_actor

          # Arguments for the git fetch command. If set to false, the action won't fetch the repo.
          # For more info as to why fetching is usually recommended, please see the "Performance on large repos" FAQ. 
          # Default: --tags --force
          fetch: false

          # The message for the commit.
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: 'Site publish'